### PR TITLE
Dat beta post

### PR DESCRIPTION
**Pull request by okdistribute**

### CODE REVIEW

**Comment by waldoj** [comment]
I'm confused by the "Merkle DAG" reference, and I'm dubious that others will know what that means. I don't want to intimidate people. Is there a better way to phrase that?

**Comment by waldoj** [comment]
I just made a pass for general edits. Tomorrow I'll make a pass for overall content, order, what might be missing, etc. I see no reason why we can't have this up tomorrow.

**Comment by max-mapper** [comment]
Yea Merkle-DAG isn't the most ideal term... but we haven't come up with anything short and sweet yet. Just short and... not sweet. I think maybe we could say 'acyclic graph (similar to git, bitcoin)' or something to make it more understandable

**Comment by waldoj** [comment]
OK, just some. This isn't bad. :)

**Comment by waldoj** [comment]
Great, let's do this.

**Comment by waldoj** [comment]
https://usopendata.org/2015/07/29/dat-beta/

**Comment by okdistribute** [comment]
@waldoj true, it isn't the most accessible word. I think though it is important to use the correct terminology for the various people who are developers that keep up with dat

**Comment by max-mapper** [comment]
hmm whats with all the whitespace?

screen shot 2015-07-29 at 10 52 57 am

**Comment by max-mapper** [comment]
in devtools if I add this rule it fixes it:

```
a { padding: 0 }
```

**Comment by waldoj** [comment]
I don't have the foggiest idea. I can't reproduce that in Chrome, Safari, or Firefox. Maybe it's a browser extension you're running?

**Comment by max-mapper** [comment]
huh, magically went away when I cleared cache. _shrug_. @waldoj what do you think about adding this for the list under 'the future':

```
li { list-style-type: disc }
```

**Comment by waldoj** [comment]
Sure! That'd look a lot better. :)

**Comment by max-mapper** [comment]
OK I tweaked it a bit, LGTM

**Comment by waldoj** [comment]
Thank you!

**Pull request merged**
