### PR TITLE
add dat beta blog post

### PR DESCRIPTION
**Pull request by okdistribute**

### CODE REVIEW

**Comment by waldoj** [comment]
Would you mind re-filing this request with the blog entry in a `/_drafts/` directory? Then we can make some edits easily.

**Comment by waldoj** [comment]
(I know it's possible to do that within a pull request, but it confuses the heck out of me. :)

**Comment by okdistribute** [comment]
@waldoj can you give me push access to the repo? Then I can make a branch directly (instead of on my own fork) so you can edit it.

**Comment by waldoj** [comment]
:+1:

**Pull request closed without merging**
